-- All existing invoices were generated by the proposal-approval flow as
-- deposits, so the new type column safely defaults to 'deposit' for legacy
-- rows. The CHECK constraint pins the canonical vocabulary.
ALTER TABLE invoices
  ADD COLUMN type text NOT NULL DEFAULT 'deposit',
  ADD CONSTRAINT invoices_type_check
    CHECK (type IN ('deposit', 'final'));

-- A project should have at most one deposit and one final invoice.
CREATE UNIQUE INDEX invoices_project_type_unique ON invoices(project_id, type);
